name: Backend Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v5

      - name: 安装 Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: 下载依赖
        run: go mod download

      - name: 编译后端
        run: go build -o blog .

      - name: 检查编译结果
        run: |
          ls -lh blog
          file blog